# Generated by Django 4.2.2 on 2023-07-09 12:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import database.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=database.models.get_attachment_upload_path
                    ),
                ),
                ("file_name", models.CharField(max_length=50)),
                ("file_type", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("middle_name", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[("student", "Студент"), ("employee", "Сотрудник")],
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("message_id", models.AutoField(primary_key=True, serialize=False)),
                ("date_received", models.DateTimeField(auto_now_add=True)),
                ("subject", models.CharField(max_length=50)),
                ("body", models.TextField()),
                ("date_sent", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_read", models.DateTimeField(null=True)),
                ("status", models.BooleanField(default=False)),
                ("important", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_sender", models.BooleanField(default=False)),
                ("deleted_recipient", models.BooleanField(default=False)),
                (
                    "attach",
                    models.ManyToManyField(
                        to="database.attachment", verbose_name="attachment"
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_messages",
                        to="database.userprofile",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="database.userprofile",
                    ),
                ),
            ],
        ),
    ]
