# Generated by Django 4.2.2 on 2023-07-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_userprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='important_recipient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='important_sender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='status_recipient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='status_sender',
            field=models.BooleanField(default=False),
        ),
    ]
