# Generated by Django 4.2.2 on 2023-07-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_userprofile_remove_messageattachment_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_recipient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_sender',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
