# Generated by Django 4.2.2 on 2023-07-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_message_important_recipient_message_important_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
